# Generated by Django 3.0.6 on 2020-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastetowealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cac_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
