# Generated by Django 3.0.6 on 2020-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastetowealth', '0002_auto_20200616_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
